spring:
  application:
    name: xcelerate-demo

server:
  servlet:
    context-path: /${spring.application.name}

info:
  name: ${spring.application.name}
  description: A service for demonstrating CI/CD
  namespace: demo-app
  project: demo
  foo: foo
  bar: bar

management:
  endpoints:
    web:
      exposure:
        include: "*"
