apiVersion: v1
kind: Pod
metadata:
  namespace: build
  labels:
    project: x-celerate-spring-application
spec:
  containers:
    - name: gradle
      image: adoptopenjdk:11-jdk-openj9
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "512Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
