---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-demo-app-run-10
spec:
  pipelineRef:
    name: "build-demo-app"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
