apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: demo-app-trigger-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: tekton
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-demo-app-run-
      spec:
        pipelineRef:
          name: build-demo-app
        params:
          - name: git-url
            value: $(tt.params.gitrepositoryurl)
          - name: git-revision
            value: $(tt.params.gitrevision)
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi
